[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
disabled = false

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
show_always = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[container]
format = '[$symbol]($style) '